# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='código')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='nome fantasia')),
                ('data_fundacao', models.DateTimeField(verbose_name='data de fundação')),
                ('inscricao_estadual', models.CharField(max_length=200, verbose_name='inscrição estadual')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='identity.Documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('sigla2', models.CharField(max_length=2, verbose_name='sigla (2)')),
                ('sigla3', models.CharField(max_length=3, verbose_name='sigla (3)')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='identity.Documento', verbose_name='documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pessoa',
                'permissions': [('can_see_pessoas_list', 'Pode visualizar todas as pessoas')],
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('abreviacao', models.CharField(max_length=10, verbose_name='abreviação')),
                ('mascara', models.CharField(max_length=100, verbose_name='máscara')),
                ('pais_vigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.Pais', verbose_name='país de vigência')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documentos',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.TipoDocumento', verbose_name='tipo do documento'),
        ),
    ]
