# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='documento_empresa',
            field=models.BooleanField(default=False, verbose_name='documento de empresa'),
            preserve_default=False,
        ),
    ]
