# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'permissions': [('own_documento', 'Pode gerenciar a própria entidade Documento')], 'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': [('own_empresas', 'Pode gerenciar as próprias entidades Empresas')], 'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': [('own_pessoa', 'Pode gerenciar a própria entidade Pessoa')], 'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
    ]
