# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_tipodocumento_documento_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='pais_vigencia',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
    ]
