# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20160320_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': [('own_pessoa', 'Pode gerenciar a própria entidade Pessoa'), ('can_see_pessoa', 'Pode visualizar outras Pessoas'), ('can_see_pessoas_list', 'Pode visualizar todas as pessoas')], 'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
    ]
