# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('data_fundacao', models.DateTimeField(verbose_name='data fundacao')),
                ('inscricao_estadual', models.CharField(max_length=200)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=16)),
                ('senha', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(verbose_name='data criacao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Pessoa')),
            ],
        ),
    ]
