# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='mascara',
            field=models.CharField(max_length=100, verbose_name='máscara'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='pais_vigencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Pais', verbose_name='país de vigência'),
        ),
    ]
