# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20160303_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla2', models.CharField(max_length=2)),
                ('sigla3', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='pais_vigencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.Pais'),
        ),
    ]
