# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20160319_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
    ]
