# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20160303_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Documento', unique=True),
        ),
    ]
