# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20160303_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Pessoa', unique=True),
        ),
    ]
