# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_auto_20160303_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Documento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Pessoa'),
        ),
    ]
