# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='event time')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='id do objeto')),
                ('parameters', models.TextField(blank=True, max_length=255, null=True, verbose_name='parameters')),
                ('message_template', models.TextField(blank=True, max_length=255, null=True, verbose_name='message')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='tipo de conteúdo')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
